services:
  - type: web
    name: jollyphonics-backend
    runtime: python
    region: oregon
    plan: free
    baseDir: backend
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: HF_REPO_ID
        value: zainabraza06/phenome_classfication
      - key: PYTHON_VERSION
        value: 3.10.13
      - key: HF_TOKEN
        sync: false          # set this manually in Render dashboard if repo is private
